/**
 * Google Apps Script — Resource Link Updater
 *
 * HOW TO USE:
 * 1. Upload your PPTX to Google Drive (it converts to Google Slides automatically)
 * 2. Upload the companion PDFs to a folder on Google Drive
 * 3. Open the Google Slides presentation
 * 4. Go to Extensions > Apps Script
 * 5. Paste this entire script into the editor (replace any existing code)
 * 6. Click Save, then Run > linkResources
 * 7. First run will ask for permissions — grant them
 * 8. A dialog will ask for the Google Drive folder URL or ID
 * 9. The script matches PDF names to resource slide text and updates hyperlinks
 *
 * MATCHING LOGIC:
 * - The script lists all PDFs in the provided folder
 * - For each PDF, it extracts the filename stem (e.g., "Session 1 Worksheet")
 * - It scans every text run on every slide for text containing that stem
 * - When found, it sets/replaces the hyperlink on that text run to point to the Drive file
 * - It also checks existing hyperlinks with broken local paths and fixes those
 *
 * WORKS WITH:
 * - Any PPTX generated by the lesson builder (resource slides use matching names)
 * - PDFs in the root of the provided folder (not nested subfolders by default)
 * - Set SEARCH_SUBFOLDERS = true below if your PDFs are in subfolders
 */

// ── Configuration ───────────────────────────────────────────────────────────

var SEARCH_SUBFOLDERS = true;  // Set to true to also search subfolders for PDFs
var LINK_MODE = "view";        // "view" = read-only link, "edit" = editable link
var SEARCH_PRESENTATION_SUBFOLDERS = false; // Set to true to also search subfolders for source decks
var IMPORT_SLIDES_AS_LINKED = false;        // true = keep imported slides linked to the source deck

// ── Main entry point ────────────────────────────────────────────────────────

function linkResources() {
  var ui = SlidesApp.getUi();

  // Ask for the folder
  var response = ui.prompt(
    "Link Resources to Google Drive",
    "Paste the Google Drive folder URL or folder ID where your PDFs are stored:\n\n" +
    "(e.g., https://drive.google.com/drive/folders/1abc... or just the ID)",
    ui.ButtonSet.OK_CANCEL
  );

  if (response.getSelectedButton() !== ui.Button.OK) {
    return;
  }

  var input = response.getResponseText().trim();
  var folderId = extractFolderId(input);

  if (!folderId) {
    ui.alert("Error", "Could not extract a folder ID from your input. Please provide a valid Google Drive folder URL or ID.", ui.ButtonSet.OK);
    return;
  }

  // Get the folder
  var folder;
  try {
    folder = DriveApp.getFolderById(folderId);
  } catch (e) {
    ui.alert("Error", "Could not access folder: " + e.message + "\n\nMake sure you have access to the folder and the ID is correct.", ui.ButtonSet.OK);
    return;
  }

  // Build PDF map: filename stem → Drive file URL
  var pdfMap = buildPdfMap(folder);
  var pdfCount = Object.keys(pdfMap).length;

  if (pdfCount === 0) {
    ui.alert("No PDFs Found", "No PDF files were found in folder: " + folder.getName() + "\n\nCheck that your PDFs are uploaded to this folder.", ui.ButtonSet.OK);
    return;
  }

  // Scan slides and update links
  var presentation = SlidesApp.getActivePresentation();
  var slides = presentation.getSlides();
  var updatedCount = 0;
  var matchLog = [];

  for (var s = 0; s < slides.length; s++) {
    var slide = slides[s];
    var elements = slide.getPageElements();

    for (var e = 0; e < elements.length; e++) {
      var element = elements[e];

      if (element.getPageElementType() === SlidesApp.PageElementType.SHAPE) {
        var shape = element.asShape();
        if (!shape.getText) continue;

        var textRange = shape.getText();
        var runs = textRange.getRuns();

        for (var r = 0; r < runs.length; r++) {
          var run = runs[r];
          var runText = run.asString().trim();
          var link = run.getTextStyle().getLink();

          // Strategy 1: Match text content to PDF names
          var matched = findBestMatch(runText, pdfMap);
          if (matched) {
            run.getTextStyle().setLinkUrl(matched.url);
            updatedCount++;
            matchLog.push("Slide " + (s + 1) + ": \"" + truncate(runText, 40) + "\" -> " + matched.name);
            continue;
          }

          // Strategy 2: Fix broken local hyperlinks
          if (link) {
            var linkUrl = "";
            try { linkUrl = link.getUrl() || ""; } catch (ex) { /* non-URL link */ }

            if (linkUrl && isLocalPath(linkUrl)) {
              var localFilename = extractFilenameFromPath(linkUrl);
              var localStem = stripExtension(localFilename);

              if (pdfMap[localStem]) {
                run.getTextStyle().setLinkUrl(pdfMap[localStem].url);
                updatedCount++;
                matchLog.push("Slide " + (s + 1) + ": fixed local link \"" + localFilename + "\" -> " + pdfMap[localStem].name);
              }
            }
          }
        }
      }

      // Also check tables
      if (element.getPageElementType() === SlidesApp.PageElementType.TABLE) {
        var table = element.asTable();
        for (var row = 0; row < table.getNumRows(); row++) {
          for (var col = 0; col < table.getNumColumns(); col++) {
            var cell = table.getCell(row, col);
            var cellRuns = cell.getText().getRuns();
            for (var cr = 0; cr < cellRuns.length; cr++) {
              var cellRun = cellRuns[cr];
              var cellText = cellRun.asString().trim();
              var cellMatched = findBestMatch(cellText, pdfMap);
              if (cellMatched) {
                cellRun.getTextStyle().setLinkUrl(cellMatched.url);
                updatedCount++;
                matchLog.push("Slide " + (s + 1) + " (table): \"" + truncate(cellText, 40) + "\" -> " + cellMatched.name);
              }
            }
          }
        }
      }
    }
  }

  // Report results
  var report = "Resource Link Update Complete\n\n";
  report += "PDFs found in folder: " + pdfCount + "\n";
  report += "Links updated: " + updatedCount + "\n\n";

  if (matchLog.length > 0) {
    report += "Matches:\n";
    for (var m = 0; m < matchLog.length; m++) {
      report += "  " + matchLog[m] + "\n";
    }
  }

  if (updatedCount === 0) {
    report += "\nNo matches found. This can happen if:\n";
    report += "- The resource slide text does not match the PDF filenames\n";
    report += "- The PDFs are in a different folder\n";
    report += "\nPDFs found:\n";
    var keys = Object.keys(pdfMap);
    for (var k = 0; k < Math.min(keys.length, 10); k++) {
      report += "  " + pdfMap[keys[k]].name + "\n";
    }
  }

  ui.alert("Results", report, ui.ButtonSet.OK);
}

/**
 * Merge all Google Slides presentations from a Drive folder into the current deck.
 * Source files are imported in natural filename order.
 */
function mergeDecksIntoCurrentPresentation() {
  var result = promptAndMergeDecks_();
  if (!result) return;
  showMergeReport_(result);
}

/**
 * Merge source decks first, then run the existing resource-link updater.
 */
function mergeDecksAndLinkResources() {
  var result = promptAndMergeDecks_();
  if (!result) return;
  showMergeReport_(result);
  linkResources();
}

// ── Helper functions ────────────────────────────────────────────────────────

/**
 * Extract folder ID from a URL or raw ID string.
 */
function extractFolderId(input) {
  if (!input) return null;

  // Full URL: https://drive.google.com/drive/folders/1abc...
  var urlMatch = input.match(/\/folders\/([a-zA-Z0-9_-]+)/);
  if (urlMatch) return urlMatch[1];

  // Full URL with ?id= parameter
  var idParamMatch = input.match(/[?&]id=([a-zA-Z0-9_-]+)/);
  if (idParamMatch) return idParamMatch[1];

  // Raw ID (no slashes, reasonable length)
  if (/^[a-zA-Z0-9_-]{10,}$/.test(input)) return input;

  return null;
}

/**
 * Build a map of PDF filename stems to Drive file URLs.
 */
function buildPdfMap(folder) {
  var map = {};

  // Get PDFs in this folder
  var files = folder.getFilesByType(MimeType.PDF);
  while (files.hasNext()) {
    var file = files.next();
    var name = file.getName();
    var stem = stripExtension(name);
    var url = file.getUrl();

    // Normalize the stem for matching
    var normalizedStem = normalizeName(stem);
    map[normalizedStem] = { name: name, url: url, stem: stem };

    // Also store the exact stem
    if (normalizedStem !== stem) {
      map[stem] = { name: name, url: url, stem: stem };
    }
  }

  // Optionally search subfolders
  if (SEARCH_SUBFOLDERS) {
    var subfolders = folder.getFolders();
    while (subfolders.hasNext()) {
      var subfolder = subfolders.next();
      var subFiles = subfolder.getFilesByType(MimeType.PDF);
      while (subFiles.hasNext()) {
        var subFile = subFiles.next();
        var subName = subFile.getName();
        var subStem = stripExtension(subName);
        var subUrl = subFile.getUrl();
        var subNormalized = normalizeName(subStem);

        if (!map[subNormalized]) {
          map[subNormalized] = { name: subName, url: subUrl, stem: subStem };
        }
        if (!map[subStem] && subNormalized !== subStem) {
          map[subStem] = { name: subName, url: subUrl, stem: subStem };
        }
      }
    }
  }

  return map;
}

/**
 * Find the best matching PDF for a given text run.
 * Returns { name, url } or null.
 */
function findBestMatch(text, pdfMap) {
  if (!text || text.length < 3) return null;

  var normalizedText = normalizeName(text);

  // Exact match on normalized name
  if (pdfMap[normalizedText]) return pdfMap[normalizedText];

  // Check if the text contains any PDF stem
  var keys = Object.keys(pdfMap);
  var bestMatch = null;
  var bestLength = 0;

  for (var i = 0; i < keys.length; i++) {
    var key = keys[i];
    var entry = pdfMap[key];
    var normalizedKey = normalizeName(key);

    // Text contains the PDF name (or vice versa)
    if (normalizedText.indexOf(normalizedKey) !== -1 || normalizedKey.indexOf(normalizedText) !== -1) {
      // Prefer longer matches (more specific)
      if (normalizedKey.length > bestLength) {
        bestMatch = entry;
        bestLength = normalizedKey.length;
      }
    }
  }

  return bestMatch;
}

/**
 * Normalize a name for fuzzy matching: lowercase, collapse whitespace,
 * remove common separators.
 */
function normalizeName(name) {
  return (name || "")
    .toLowerCase()
    .replace(/[_\-]+/g, " ")
    .replace(/\.pdf$/i, "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Strip file extension from a filename.
 */
function stripExtension(filename) {
  return (filename || "").replace(/\.[^.]+$/, "");
}

/**
 * Check if a URL looks like a local/relative file path (not a web URL).
 */
function isLocalPath(url) {
  if (!url) return false;
  // Local paths: no protocol, or file:// protocol, or relative paths
  return !url.match(/^https?:\/\//) || url.indexOf("file://") === 0;
}

/**
 * Extract filename from a local path (handles both / and \).
 */
function extractFilenameFromPath(path) {
  if (!path) return "";
  var parts = path.replace(/\\/g, "/").split("/");
  return parts[parts.length - 1] || "";
}

/**
 * Truncate a string for display.
 */
function truncate(str, maxLen) {
  if (!str) return "";
  if (str.length <= maxLen) return str;
  return str.substring(0, maxLen - 3) + "...";
}

/**
 * Prompt for a Drive folder and merge all Google Slides presentations found there.
 * Returns a summary object or null if the user cancels.
 */
function promptAndMergeDecks_() {
  var ui = SlidesApp.getUi();
  var response = ui.prompt(
    "Merge Lesson Decks",
    "Paste the Google Drive folder URL or folder ID that contains the source Google Slides decks:\n\n" +
    "(Files are imported in natural filename order, for example Session 1, Session 2, ... Session 10.)",
    ui.ButtonSet.OK_CANCEL
  );

  if (response.getSelectedButton() !== ui.Button.OK) {
    return null;
  }

  var input = response.getResponseText().trim();
  var folderId = extractFolderId(input);
  if (!folderId) {
    ui.alert("Error", "Could not extract a folder ID from your input. Please provide a valid Google Drive folder URL or ID.", ui.ButtonSet.OK);
    return null;
  }

  var folder;
  try {
    folder = DriveApp.getFolderById(folderId);
  } catch (e) {
    ui.alert("Error", "Could not access folder: " + e.message + "\n\nMake sure you have access to the folder and the ID is correct.", ui.ButtonSet.OK);
    return null;
  }

  var sourceFiles = collectPresentationFiles_(folder);
  if (sourceFiles.length === 0) {
    ui.alert(
      "No Google Slides Decks Found",
      "No Google Slides presentations were found in folder: " + folder.getName() + "\n\n" +
      "Upload or convert the source PPTX files to Google Slides first, then run the merge again.",
      ui.ButtonSet.OK
    );
    return null;
  }

  sourceFiles.sort(compareDriveFilesByName_);

  var presentation = SlidesApp.getActivePresentation();
  var existingSlides = presentation.getSlides().slice();
  var replaceCurrentSlides = false;

  if (existingSlides.length > 0) {
    var replaceResponse = ui.alert(
      "Replace Current Slides?",
      "Yes: import the source decks, then remove the slides currently in this presentation.\n" +
      "No: keep the current slides and append the imported decks after them.",
      ui.ButtonSet.YES_NO_CANCEL
    );

    if (replaceResponse === ui.Button.CANCEL) {
      return null;
    }

    replaceCurrentSlides = replaceResponse === ui.Button.YES;
  }

  var importedDeckNames = [];
  var skippedDeckNames = [];
  var importedDeckCount = 0;
  var importedSlideCount = 0;

  for (var i = 0; i < sourceFiles.length; i++) {
    var file = sourceFiles[i];

    if (file.id === presentation.getId()) {
      skippedDeckNames.push(file.name + " (current target presentation)");
      continue;
    }

    var sourcePresentation;
    try {
      sourcePresentation = SlidesApp.openById(file.id);
    } catch (e) {
      skippedDeckNames.push(file.name + " (could not open: " + e.message + ")");
      continue;
    }

    var sourceSlides = sourcePresentation.getSlides();
    if (sourceSlides.length === 0) {
      skippedDeckNames.push(file.name + " (no slides)");
      continue;
    }

    for (var s = 0; s < sourceSlides.length; s++) {
      if (IMPORT_SLIDES_AS_LINKED) {
        presentation.appendSlide(sourceSlides[s], SlidesApp.SlideLinkingMode.LINKED);
      } else {
        presentation.appendSlide(sourceSlides[s]);
      }
      importedSlideCount++;
    }

    importedDeckCount++;
    importedDeckNames.push(file.name + " (" + sourceSlides.length + " slides)");
  }

  if (replaceCurrentSlides && importedSlideCount > 0) {
    removeSlides_(existingSlides);
  }

  return {
    folderName: folder.getName(),
    importedDeckCount: importedDeckCount,
    importedSlideCount: importedSlideCount,
    importedDeckNames: importedDeckNames,
    skippedDeckNames: skippedDeckNames,
    replaceCurrentSlides: replaceCurrentSlides,
    importSlidesAsLinked: IMPORT_SLIDES_AS_LINKED
  };
}

/**
 * Collect Google Slides files from a folder, optionally including subfolders.
 */
function collectPresentationFiles_(folder) {
  var files = [];
  collectPresentationFilesInto_(folder, files);
  return files;
}

function collectPresentationFilesInto_(folder, files) {
  var iter = folder.getFiles();
  while (iter.hasNext()) {
    var file = iter.next();
    if (file.getMimeType() === MimeType.GOOGLE_SLIDES) {
      files.push({
        id: file.getId(),
        name: file.getName()
      });
    }
  }

  if (!SEARCH_PRESENTATION_SUBFOLDERS) {
    return;
  }

  var subfolders = folder.getFolders();
  while (subfolders.hasNext()) {
    collectPresentationFilesInto_(subfolders.next(), files);
  }
}

/**
 * Natural sort for Drive filenames so Session 2 appears before Session 10.
 */
function compareDriveFilesByName_(a, b) {
  return a.name.localeCompare(b.name, undefined, { numeric: true, sensitivity: "base" });
}

/**
 * Remove slides from a presentation after imports succeed.
 */
function removeSlides_(slides) {
  for (var i = 0; i < slides.length; i++) {
    slides[i].remove();
  }
}

/**
 * Display a merge summary.
 */
function showMergeReport_(result) {
  var ui = SlidesApp.getUi();
  var report = "Deck Merge Complete\n\n";
  report += "Source folder: " + result.folderName + "\n";
  report += "Decks imported: " + result.importedDeckCount + "\n";
  report += "Slides imported: " + result.importedSlideCount + "\n";
  report += "Current slides replaced: " + (result.replaceCurrentSlides ? "yes" : "no") + "\n";
  report += "Import mode: " + (result.importSlidesAsLinked ? "linked" : "standard copy") + "\n\n";

  if (result.importedDeckNames.length > 0) {
    report += "Imported decks:\n";
    for (var i = 0; i < result.importedDeckNames.length; i++) {
      report += "  " + result.importedDeckNames[i] + "\n";
    }
  }

  if (result.skippedDeckNames.length > 0) {
    report += "\nSkipped:\n";
    for (var j = 0; j < result.skippedDeckNames.length; j++) {
      report += "  " + result.skippedDeckNames[j] + "\n";
    }
  }

  ui.alert("Results", report, ui.ButtonSet.OK);
}

// ── Menu integration ────────────────────────────────────────────────────────

/**
 * Adds a custom menu item when the presentation is opened.
 */
function onOpen() {
  SlidesApp.getUi()
    .createMenu("Resource Tools")
    .addItem("Merge Decks Into This Presentation", "mergeDecksIntoCurrentPresentation")
    .addItem("Merge Decks + Link Resources", "mergeDecksAndLinkResources")
    .addSeparator()
    .addItem("Link Resources to Google Drive", "linkResources")
    .addToUi();
}
